# This configuration compares LLM output of 2 prompts x 2 GPT models across 3 test cases.
# Learn more: https://promptfoo.dev/docs/configuration/guide
description: 'My first eval'

prompts:
  - "Write a tweet about {{topic}}"
  - "Write a very concise, funny tweet about {{topic}}"

providers:
  - id: 'python:provider.py'
    config:
      additionalOption: llama
  - id: 'python:provider.py'
    config:
      additionalOption: phi

tests:
  - description: 'Tweet about bananas'
    vars:
      topic: bananas
    assert:
      - type: similar
        value: Bananas are nice
        provider: huggingface:sentence-similarity:sentence-transformers/all-MiniLM-L6-v2
